import Foundation
import Testing
@testable import SpoolMesh

private let realHeader = """
; generated by PrusaSlicer 2.7.0+win64 on 2026-01-15 at 10:30:00
; external perimeters extrusion width = 0.45mm
G28 ; home all axes
"""

private let realFooter = """
; filament used [mm] = 3200.50
; filament used [cm3] = 7.68
; filament used [g] = 9.60
; filament cost = 0.24
; estimated printing time (normal mode) = 1h 2m 3s
; estimated printing time (silent mode) = 1h 10m 0s

; prusaslicer_config = begin
; avoid_crossing_perimeters = 0
; nozzle_diameter = 0.4,0.4,0.4,0.4
; layer_height = 0.2
; fill_density = 15%
; filament_type = PLA
; printer_model = MK3S
; prusaslicer_config = end
"""

@Suite struct GcodeMetadataExtractorTests {
    @Test func extractsFullMetadataFromARealPrusaSlicerFooter() {
        let metadata = GcodeMetadataExtractor.extract(headerText: realHeader, footerText: realFooter)
        let unwrapped = try! #require(metadata)

        #expect(unwrapped.nozzleDiameterMM == 0.4)
        #expect(unwrapped.layerHeightMM == 0.2)
        #expect(unwrapped.infillPercent == 15)
        #expect(unwrapped.material == "PLA")
        #expect(unwrapped.printerModel == "MK3S")
        #expect(unwrapped.filamentUsedGrams == 9.60)
        // 1h 2m 3s sits almost exactly on a rounding tie (62.05), where Swift's
        // round-half-away-from-zero and Python's round-half-to-even (compounded by
        // IEEE754 representation quirks right at the tie) can legitimately disagree by
        // 0.1 — a tolerance check here, exact-match rounding is verified separately
        // below with a fixture that isn't sitting on a tie.
        #expect(abs((unwrapped.estimatedPrintMinutes ?? 0) - 62.05) < 0.15)
        // Only the two tokens right after "generated by" (slicer name + version) —
        // not the trailing "on <date> at <time>" the real PrusaSlicer header adds.
        #expect(unwrapped.slicerVersion == "PrusaSlicer 2.7.0+win64")
    }

    @Test func durationParsingHandlesHoursMinutesSecondsAndRoundsToOneDecimal() {
        // Matches the source app's `round(total, 1)` exactly: 9h 8m 25s is
        // 548.41666...-repeating minutes, which must come out as 548.4, not the
        // unrounded value.
        let footer = """
            ; estimated printing time (normal mode) = 9h 8m 25s
            ; prusaslicer_config = begin
            ; nozzle_diameter = 0.4
            ; prusaslicer_config = end
            """
        let metadata = try! #require(GcodeMetadataExtractor.extract(headerText: "", footerText: footer))
        #expect(metadata.estimatedPrintMinutes == 548.4)
    }

    @Test func prefersTotalFilamentUsedOverThePerSegmentValue() {
        // A multi-object print's per-segment "filament used [g]" can differ from the
        // "total filament used [g]" summed across the whole plate — the total is the
        // one that actually matters, regardless of which line appears first.
        let footer = """
            ; filament used [g] = 243.32
            ; total filament used [g] = 500.0
            ; prusaslicer_config = begin
            ; nozzle_diameter = 0.4
            ; prusaslicer_config = end
            """
        let metadata = try! #require(GcodeMetadataExtractor.extract(headerText: "", footerText: footer))
        #expect(metadata.filamentUsedGrams == 500.0)
    }

    @Test func returnsNilWhenFooterHasNoRecognizedSlicerDump() {
        let footer = "; just some random comment\nG28\n"
        #expect(GcodeMetadataExtractor.extract(headerText: "", footerText: footer) == nil)
    }

    @Test func worksForOtherSlicerLineageConfigBlockNames() {
        // OrcaSlicer/SuperSlicer use their own `_config = begin/end` marker names but
        // the same key names inside — the parser shouldn't hardcode "prusaslicer".
        let footer = """
            ; orcaslicer_config = begin
            ; nozzle_diameter = 0.4
            ; printer_model = X1 Carbon
            ; orcaslicer_config = end
            """
        let metadata = try! #require(GcodeMetadataExtractor.extract(headerText: "", footerText: footer))
        #expect(metadata.printerModel == "X1 Carbon")
    }
}
