import AppKit
import Foundation
import Testing
@testable import SpoolMesh

/// Draws directly into a fixed-pixel-size `NSBitmapImageRep` rather than going through
/// `NSImage`/`lockFocus()`, which scales by the host display's backing factor (2x on
/// Retina) — that would make the produced PNG's actual pixel dimensions silently differ
/// from `pixelSize`, which is exactly what this fixture needs to be exact about.
private func makePNGBase64(pixelSize: Int) -> String {
    let bitmap = NSBitmapImageRep(
        bitmapDataPlanes: nil,
        pixelsWide: pixelSize,
        pixelsHigh: pixelSize,
        bitsPerSample: 8,
        samplesPerPixel: 4,
        hasAlpha: true,
        isPlanar: false,
        colorSpaceName: .deviceRGB,
        bytesPerRow: 0,
        bitsPerPixel: 0
    )!
    NSGraphicsContext.saveGraphicsState()
    NSGraphicsContext.current = NSGraphicsContext(bitmapImageRep: bitmap)
    NSColor.red.setFill()
    NSRect(x: 0, y: 0, width: pixelSize, height: pixelSize).fill()
    NSGraphicsContext.restoreGraphicsState()
    let png = bitmap.representation(using: .png, properties: [:])!
    return png.base64EncodedString()
}

/// Real slicers wrap the base64 payload at a fixed column width — replicate that so the
/// parser is exercised against realistic multi-line blocks, not one giant line.
private func wrapBase64(_ base64: String, width: Int = 78) -> [String] {
    var lines: [String] = []
    var remaining = Substring(base64)
    while !remaining.isEmpty {
        let end = remaining.index(remaining.startIndex, offsetBy: min(width, remaining.count))
        lines.append("; " + remaining[remaining.startIndex..<end])
        remaining = remaining[end...]
    }
    return lines
}

@Suite struct GcodeThumbnailExtractorTests {
    @Test func extractsSingleEmbeddedThumbnail() {
        let base64 = makePNGBase64(pixelSize: 4)
        var text = "; generated by PrusaSlicer 2.7.0\n"
        text += "; thumbnail begin 4x4 \(base64.count)\n"
        text += wrapBase64(base64).joined(separator: "\n") + "\n"
        text += "; thumbnail end\n"
        text += "G28 ; home\n"

        let data = GcodeThumbnailExtractor.extractLargestThumbnail(fromHeaderText: text)
        #expect(data != nil)
        if let data, let bitmap = NSBitmapImageRep(data: data) {
            #expect(bitmap.pixelsWide == 4)
        }
    }

    @Test func picksTheLargestOfMultipleThumbnails() {
        let small = makePNGBase64(pixelSize: 2)
        let large = makePNGBase64(pixelSize: 8)
        var text = "; generated by PrusaSlicer 2.7.0\n"
        text += "; thumbnail begin 2x2 \(small.count)\n" + wrapBase64(small).joined(separator: "\n") + "\n; thumbnail end\n"
        text += "; thumbnail begin 8x8 \(large.count)\n" + wrapBase64(large).joined(separator: "\n") + "\n; thumbnail end\n"

        let data = GcodeThumbnailExtractor.extractLargestThumbnail(fromHeaderText: text)
        #expect(data != nil)
        if let data, let bitmap = NSBitmapImageRep(data: data) {
            #expect(bitmap.pixelsWide == 8, "should keep the larger of the two embedded thumbnails")
        }
    }

    @Test func noThumbnailBlockReturnsNil() {
        let text = "; generated by PrusaSlicer 2.7.0\n; nozzle_diameter = 0.4\nG28 ; home\n"
        #expect(GcodeThumbnailExtractor.extractLargestThumbnail(fromHeaderText: text) == nil)
    }
}
