import Foundation

/// Fields extracted from a Prusa-lineage (PrusaSlicer/SuperSlicer/OrcaSlicer — shared
/// config key names) gcode footer.
public struct GcodeMetadata: Sendable, Equatable {
    public var nozzleDiameterMM: Double?
    public var layerHeightMM: Double?
    public var infillPercent: Double?
    public var material: String?
    public var printerModel: String?
    public var filamentUsedGrams: Double?
    public var estimatedPrintMinutes: Double?
    public var slicerVersion: String?
}

/// Reads a gcode file's footer (the full print profile dump, always at the end — never
/// scans the toolpath body, which can run to tens of MB) and its first few KB (the
/// `; generated by <Slicer> <version>` line, always first). Returns `nil` if neither
/// `nozzle_diameter` nor `printer_model` is found anywhere — that means the footer
/// isn't a recognized slicer config dump (e.g. a hand-authored gcode), not that a
/// couple of fields happened to be unset.
public enum GcodeMetadataExtractor {
    private static let footerScanBytes = 300_000
    private static let headerScanBytes = 4_000

    public static func extract(url: URL) throws -> GcodeMetadata? {
        guard let handle = FileHandle(forReadingAtPath: url.path) else { return nil }
        defer { try? handle.close() }
        let fileSize = ((try? FileManager.default.attributesOfItem(atPath: url.path))?[.size] as? Int) ?? 0

        try? handle.seek(toOffset: 0)
        let headerData = try handle.read(upToCount: headerScanBytes) ?? Data()
        let headerText = String(data: headerData, encoding: .utf8) ?? String(data: headerData, encoding: .isoLatin1) ?? ""

        let footerStart = UInt64(max(0, fileSize - footerScanBytes))
        try? handle.seek(toOffset: footerStart)
        let footerData = try handle.read(upToCount: footerScanBytes) ?? Data()
        let footerText = String(data: footerData, encoding: .utf8) ?? String(data: footerData, encoding: .isoLatin1) ?? ""

        return extract(headerText: headerText, footerText: footerText)
    }

    static func extract(headerText: String, footerText: String) -> GcodeMetadata? {
        var metadata = GcodeMetadata()
        metadata.slicerVersion = slicerVersion(fromHeader: headerText)

        var configDict: [String: String] = [:]
        var inConfigBlock = false
        // A multi-object print's per-segment "filament used [g]" can differ from the
        // "total filament used [g]" summed across the whole plate — the total is the
        // one that actually matters, and always wins over the plain line regardless of
        // which order the two appear in (tracked separately so neither line's presence
        // depends on the other having already been seen).
        var filamentUsedTotal: Double?
        var filamentUsedPlain: Double?
        for rawLine in footerText.split(separator: "\n", omittingEmptySubsequences: false) {
            let line = rawLine.trimmingCharacters(in: .whitespaces)

            if line.hasSuffix("_config = begin") {
                inConfigBlock = true
                continue
            }
            if line.hasSuffix("_config = end") {
                inConfigBlock = false
                continue
            }
            if inConfigBlock {
                guard line.hasPrefix(";"), let (key, value) = keyValue(fromConfigLine: String(line.dropFirst())) else { continue }
                configDict[key] = value
                continue
            }

            // Loose summary lines (no begin/end markers), before the config block. A
            // footer can have both "(normal mode)" and "(silent mode)" printing-time
            // lines — normal mode always wins if present, regardless of which line
            // comes first in the file, rather than whichever happens to be seen last.
            if line.hasPrefix("; total filament used [g]"), let value = valueAfterEquals(line) {
                filamentUsedTotal = Double(value)
            } else if line.hasPrefix("; filament used [g]"), let value = valueAfterEquals(line) {
                filamentUsedPlain = Double(value)
            } else if line.hasPrefix("; estimated printing time (normal mode)"), let value = valueAfterEquals(line) {
                metadata.estimatedPrintMinutes = parseDurationToMinutes(value)
            } else if line.hasPrefix("; estimated printing time"), metadata.estimatedPrintMinutes == nil,
                      let value = valueAfterEquals(line) {
                metadata.estimatedPrintMinutes = parseDurationToMinutes(value)
            }
        }
        metadata.filamentUsedGrams = filamentUsedTotal ?? filamentUsedPlain

        metadata.nozzleDiameterMM = configDict["nozzle_diameter"].flatMap(firstNumber)
        metadata.layerHeightMM = configDict["layer_height"].flatMap { Double($0) }
        metadata.infillPercent = configDict["fill_density"].flatMap(percentValue)
        metadata.material = configDict["filament_type"].flatMap(firstToken)
        metadata.printerModel = configDict["printer_model"]

        guard metadata.nozzleDiameterMM != nil || metadata.printerModel != nil else { return nil }
        return metadata
    }

    /// Only the first two whitespace-separated tokens after "generated by" (slicer name
    /// + version) — not the rest of the line, which some slicers follow with
    /// " on <date> at <time>" that isn't part of the version string.
    private static func slicerVersion(fromHeader text: String) -> String? {
        for rawLine in text.split(separator: "\n") {
            let line = rawLine.trimmingCharacters(in: .whitespaces)
            guard line.lowercased().hasPrefix("; generated by ") else { continue }
            let rest = line.dropFirst("; generated by ".count)
            let tokens = rest.split(separator: " ", omittingEmptySubsequences: true)
            guard tokens.count >= 2 else { return nil }
            return "\(tokens[0]) \(tokens[1])"
        }
        return nil
    }

    private static func keyValue(fromConfigLine line: String) -> (String, String)? {
        guard let eqIndex = line.firstIndex(of: "=") else { return nil }
        let key = line[line.startIndex..<eqIndex].trimmingCharacters(in: .whitespaces)
        let value = line[line.index(after: eqIndex)...].trimmingCharacters(in: .whitespaces)
        return key.isEmpty ? nil : (key, value)
    }

    private static func valueAfterEquals(_ line: String) -> String? {
        guard let eqIndex = line.firstIndex(of: "=") else { return nil }
        return line[line.index(after: eqIndex)...].trimmingCharacters(in: .whitespaces)
    }

    /// Handles multi-extruder values like `"0.4,0.4,0.4,0.4"` by taking the first.
    private static func firstNumber(_ text: String) -> Double? {
        let token = text.split(separator: ",").first.map(String.init) ?? text
        return Double(token.trimmingCharacters(in: .whitespaces))
    }

    private static func firstToken(_ text: String) -> String? {
        let token = text.split(separator: ";").first ?? text.split(separator: ",").first ?? Substring(text)
        let trimmed = token.trimmingCharacters(in: .whitespaces)
        return trimmed.isEmpty ? nil : trimmed
    }

    private static func percentValue(_ text: String) -> Double? {
        let trimmed = text.hasSuffix("%") ? String(text.dropLast()) : text
        return Double(trimmed)
    }

    /// Parses `"1h 2m 3s"`-style durations (any subset/order of d/h/m/s components,
    /// PrusaSlicer's own format) into total minutes.
    private static func parseDurationToMinutes(_ text: String) -> Double? {
        guard let regex = try? NSRegularExpression(pattern: #"(\d+)\s*([dhms])"#) else { return nil }
        let range = NSRange(text.startIndex..<text.endIndex, in: text)
        var totalSeconds = 0.0
        var foundAny = false
        regex.enumerateMatches(in: text, range: range) { match, _, _ in
            guard let match,
                  let numberRange = Range(match.range(at: 1), in: text),
                  let unitRange = Range(match.range(at: 2), in: text),
                  let value = Double(text[numberRange]) else { return }
            let multiplier: Double
            switch text[unitRange] {
            case "d": multiplier = 86400
            case "h": multiplier = 3600
            case "m": multiplier = 60
            case "s": multiplier = 1
            default: multiplier = 0
            }
            totalSeconds += value * multiplier
            foundAny = true
        }
        guard foundAny else { return nil }
        // Matches the original's `round(total, 1)` — without this, "9h 8m 25s" comes
        // out as 548.41666...66 instead of the expected 548.4.
        return (totalSeconds / 60.0 * 10).rounded() / 10
    }
}
