import AppKit
import Foundation
import GRDB
import Testing
@testable import SpoolCore

/// End-to-end verification of the M1 core loop — Backfill discovers real files on
/// disk, the job queue hashes and renders them through the real handlers (not mocks),
/// and the results land back in the database and on disk exactly as the browse UI
/// would read them.
@Suite struct RenderPipelineIntegrationTests {
    private func makeTempDir() throws -> URL {
        let dir = FileManager.default.temporaryDirectory.appendingPathComponent("SpoolCoreTests-\(UUID().uuidString)")
        try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        return dir
    }

    private func writeCubeSTL(to url: URL) throws {
        var data = Data(count: 80)
        data.append(contentsOf: withUnsafeBytes(of: UInt32(12).littleEndian) { Array($0) })
        let corners: [SIMD3<Float>] = [
            [0, 0, 0], [1, 0, 0], [1, 1, 0], [0, 1, 0],
            [0, 0, 1], [1, 0, 1], [1, 1, 1], [0, 1, 1],
        ]
        let faces: [(Int, Int, Int)] = [
            (0, 3, 2), (0, 2, 1), (4, 5, 6), (4, 6, 7), (0, 1, 5), (0, 5, 4),
            (1, 2, 6), (1, 6, 5), (2, 3, 7), (2, 7, 6), (3, 0, 4), (3, 4, 7),
        ]
        for (a, b, c) in faces {
            data.append(contentsOf: [UInt8](repeating: 0, count: 12))
            for idx in [a, b, c] {
                let v = corners[idx]
                data.append(contentsOf: withUnsafeBytes(of: v.x) { Array($0) })
                data.append(contentsOf: withUnsafeBytes(of: v.y) { Array($0) })
                data.append(contentsOf: withUnsafeBytes(of: v.z) { Array($0) })
            }
            data.append(contentsOf: [0, 0])
        }
        try data.write(to: url)
    }

    private func writeGcodeWithThumbnail(to url: URL) throws {
        let bitmap = NSBitmapImageRep(
            bitmapDataPlanes: nil, pixelsWide: 4, pixelsHigh: 4, bitsPerSample: 8,
            samplesPerPixel: 4, hasAlpha: true, isPlanar: false, colorSpaceName: .deviceRGB,
            bytesPerRow: 0, bitsPerPixel: 0
        )!
        NSGraphicsContext.saveGraphicsState()
        NSGraphicsContext.current = NSGraphicsContext(bitmapImageRep: bitmap)
        NSColor.blue.setFill()
        NSRect(x: 0, y: 0, width: 4, height: 4).fill()
        NSGraphicsContext.restoreGraphicsState()
        let png = bitmap.representation(using: .png, properties: [:])!
        let base64 = png.base64EncodedString()

        var text = "; generated by PrusaSlicer 2.7.0\n"
        text += "; thumbnail begin 4x4 \(base64.count)\n"
        var remaining = Substring(base64)
        while !remaining.isEmpty {
            let end = remaining.index(remaining.startIndex, offsetBy: min(78, remaining.count))
            text += "; " + remaining[remaining.startIndex..<end] + "\n"
            remaining = remaining[end...]
        }
        text += "; thumbnail end\nG28 ; home\n"
        try text.write(to: url, atomically: true, encoding: .utf8)
    }

    @Test func backfillIngestsAndRendersRealFilesEndToEnd() async throws {
        let database = try SQLiteSpoolDatabase(path: nil)
        let tempDir = try makeTempDir()
        defer { try? FileManager.default.removeItem(at: tempDir) }
        let thumbsDir = tempDir.appendingPathComponent("Thumbnails")
        try FileManager.default.createDirectory(at: thumbsDir, withIntermediateDirectories: true)
        let libraryDir = tempDir.appendingPathComponent("Library")
        try FileManager.default.createDirectory(at: libraryDir, withIntermediateDirectories: true)

        try writeCubeSTL(to: libraryDir.appendingPathComponent("cube.stl"))
        try writeGcodeWithThumbnail(to: libraryDir.appendingPathComponent("part.gcode"))
        try "module widget() {}".write(
            to: libraryDir.appendingPathComponent("widget.scad"), atomically: true, encoding: .utf8
        )

        let root = try await database.writer.write { conn in
            try WatchedRoot(hostPath: libraryDir.path, label: "Library", kind: .library, bookmarkData: Data())
                .inserted(conn)
        }

        let deferredEnqueuer = DeferredJobEnqueuer()
        let handlers = JobHandlers(
            ingest: IngestJobHandler(writer: database.writer, enqueuer: deferredEnqueuer),
            render: RenderJobHandler(writer: database.writer, thumbnailsDirectory: thumbsDir),
            renderStep: UnsupportedFormatJobHandler(writer: database.writer),
            rescan: NoOpJobHandler(),
            extractZip: NoOpJobHandler()
        )
        let jobQueue = JobQueue(writer: database.writer, handlers: handlers)
        await deferredEnqueuer.attach(jobQueue)
        await jobQueue.start()

        let backfillService = BackfillService(writer: database.writer, enqueuer: jobQueue)
        let stagedCount = try await backfillService.run(root: root, rootURL: libraryDir)
        #expect(stagedCount == 3)

        try await waitUntilAllFilesAreTerminal(database: database, expectedCount: 3)

        let files = try await database.writer.read { conn in
            try SpoolFile.order(Column("filename")).fetchAll(conn)
        }
        #expect(files.count == 3)

        let cube = try #require(files.first(where: { $0.filename == "cube.stl" }))
        #expect(cube.contentHash?.count == 64)
        #expect(cube.renderStatus == .done)
        #expect(cube.isManifold == true)
        #expect(cube.triCount == 12)
        #expect(cube.volumeMm3 != nil)
        let cubeThumbPath = try #require(cube.thumbnailPath)
        let cubeThumbURL = thumbsDir.appendingPathComponent(cubeThumbPath)
        #expect(FileManager.default.fileExists(atPath: cubeThumbURL.path))
        if let bitmap = NSBitmapImageRep(data: try Data(contentsOf: cubeThumbURL)) {
            #expect(bitmap.pixelsWide == 512, "default thumbnail size")
        }

        let gcode = try #require(files.first(where: { $0.filename == "part.gcode" }))
        #expect(gcode.renderStatus == .done)
        let gcodeThumbPath = try #require(gcode.thumbnailPath)
        #expect(FileManager.default.fileExists(atPath: thumbsDir.appendingPathComponent(gcodeThumbPath).path))

        let scad = try #require(files.first(where: { $0.filename == "widget.scad" }))
        #expect(scad.renderStatus == .unsupported)
        #expect(scad.thumbnailPath == nil)
        #expect(scad.contentHash?.count == 64, "still hashed/tracked even with no preview")

        await jobQueue.stop()
    }

    private func waitUntilAllFilesAreTerminal(
        database: SQLiteSpoolDatabase,
        expectedCount: Int,
        timeout: Duration = .seconds(10)
    ) async throws {
        let terminal: Set<FileRenderStatus> = [.done, .failed, .unsupported]
        let deadline = ContinuousClock.now + timeout
        while ContinuousClock.now < deadline {
            let files = try await database.writer.read { conn in try SpoolFile.fetchAll(conn) }
            if files.count == expectedCount, files.allSatisfy({ terminal.contains($0.renderStatus) }) {
                return
            }
            try await Task.sleep(for: .milliseconds(20))
        }
        Issue.record("files did not reach a terminal render_status within \(timeout)")
    }
}
